[package]
name = "pacd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
liquid = "0.26.0"
regex = "1.7.1"
serde_json = "1.0.91"
walkdir = "2.3.2"
